# Generated by Django 5.1.6 on 2025-02-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-votes', '-date_added']},
        ),
        migrations.AddField(
            model_name='show',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
