# Generated by Django 5.1.6 on 2025-02-18 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_show_options_show_image_url_show_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
