# Generated by Django 5.1.6 on 2025-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_lifeevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='backdrop_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='director',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='episode_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='last_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='original_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='personal_rating',
            field=models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='production_companies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='season_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='watch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='watch_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
