# Generated by Django 5.1.6 on 2025-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_show_tmdb_id_show_unique_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Currently Watching'), ('watched', 'Finished Watching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='watch_status',
            field=models.CharField(blank=True, choices=[('', 'Not Started'), ('started', 'Started Watching'), ('completed', 'Completed')], default='', max_length=50),
        ),
    ]
