# Generated by Django 5.1.6 on 2025-02-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_show_status_alter_show_watch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeevent',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='life_events', to='portfolio.show'),
        ),
    ]
