# Generated by Django 5.1.6 on 2025-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_lifeevent_book_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
